# ==================== Basic driver configuration ====================
CONFIG_SPI=y                   
CONFIG_INPUT=y                  
CONFIG_ZMK_MOUSE=y          
CONFIG_ZMK_EXT_POWER=y        

# ==================== PMW3610 Basic Configuration ====================
CONFIG_PMW3610=y                           
CONFIG_PMW3610_CPI=1600                     
CONFIG_PMW3610_CPI_DIVIDOR=4                
CONFIG_PMW3610_ORIENTATION_90=y            
CONFIG_PMW3610_INVERT_X=y                 

# ==================== PMW3610 Function Configuration ====================
CONFIG_PMW3610_SNIPE_CPI=200                
CONFIG_PMW3610_SNIPE_CPI_DIVIDOR=1          
CONFIG_PMW3610_SCROLL_TICK=70               
CONFIG_PMW3610_POLLING_RATE_125_SW=y
# Default is y
CONFIG_PMW3610_SMART_ALGORITHM=n
# Liviu Setted default 250
CONFIG_PMW3610_AUTOMOUSE_TIMEOUT_MS=500

# ==================== PMW3610 power consumption configuration ====================
CONFIG_PMW3610_REST1_SAMPLE_TIME_MS=100    
CONFIG_PMW3610_REST2_SAMPLE_TIME_MS=200    
CONFIG_PMW3610_REST3_SAMPLE_TIME_MS=300   
CONFIG_PMW3610_RUN_DOWNSHIFT_TIME_MS=500   
CONFIG_PMW3610_REST1_DOWNSHIFT_TIME_MS=3000  
CONFIG_PMW3610_REST2_DOWNSHIFT_TIME_MS=30000 
